name: PR
on:
  pull_request:

jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
      - run: go test -race ./...

  docker-lint:
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
    with:
      dockerfile: Dockerfile
      ignore: DL3018

  docker-build:
    uses: ./.github/workflows/build.yml
    with:
      dockerfile: Dockerfile
      context: .

  docker-scan:
    needs: docker-build
    uses: entur/gha-security/.github/workflows/docker-scan.yml@v2
    with:
      image_artifact: ${{ needs.docker-build.outputs.image_artifact }}

  trigger-downstream-ci:
    # only build and push the image when it's a commit to master in Entur's repository
    runs-on: ubuntu-latest
    needs: [ docker-build, docker-scan ]
    env:
      ARTIFACT_NAME: ${{ needs.docker-build.outputs.image_artifact }}
      RUN_ID: ${{ github.run_id }}
      REPOSITORY: ${{ github.repository }}
      EVENT_TYPE: trigger-downstream-ci
    steps:
      - name: Trigger downstream CI
        run: |
          repository="${{ env.REPOSITORY }}"
          event_type="${{ env.EVENT_TYPE }}"
          echo "Triggering downstream CI for $repository with docker artifact ${{ env.ARTIFACT_NAME }}"
          curl -X POST \
          -H "Authorization: token ${{ secrets.OSS_TEST_PAT }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/$repository/dispatches \
          -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"artifact_name\": \"${{ env.ARTIFACT_NAME }}\", \"run_id\": \"${{ env.RUN_ID }}\" }}"